apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akswangyao1025"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akswangyao1025"
  template:
    metadata:
      labels:
        app: "akswangyao1025"
    spec:
      containers:
        - name: "test"
          image: "acrworkflow1677122162587.azurecr.io/test"
          ports:
          - containerPort: 80
