apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akswangyao1025"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akswangyao1025"
  template:
    metadata:
      labels:
        app: "akswangyao1025"
    spec:
      containers:
        - name: "image1025"
          image: "ywregistry1025.azurecr.io/image1025"
          ports:
          - containerPort: 80
