apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akswangyao1201-991a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akswangyao1201-991a"
  template:
    metadata:
      labels:
        app: "akswangyao1201-991a"
    spec:
      containers:
        - name: "akswangyao1201-991a"
          image: "wyregistry.azurecr.io/akswangyao1201"
          ports:
          - containerPort: 80