on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: sptestregistrynew.azurecr.io
        username: ${{ secrets.acr_sptestregistrynew_username }}
        password: ${{ secrets.acr_sptestregistrynew_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sptestregistrynew.azurecr.io/akswangyao1025:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push sptestregistrynew.azurecr.io/akswangyao1025:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akswangyao1025_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep go-echo-1025 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace go-echo-1025`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: go-echo-1025
        container-registry-url: sptestregistrynew.azurecr.io
        container-registry-username: ${{ secrets.acr_sptestregistrynew_username }}
        container-registry-password: ${{ secrets.acr_sptestregistrynew_password }}
        secret-name: akswangyao10dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: go-echo-1025
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          sptestregistrynew.azurecr.io/akswangyao1025:${{ github.sha }}
        imagepullsecrets: |
          akswangyao10dockerauth
